gsap.registerPlugin(ScrollTrigger);
gsap.fromTo('.banner_image', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.banner_image', toggleActions: 'restart none none none'}, duration: 1.5, opacity: 1, y: 0,});
gsap.fromTo('.banner_text', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.banner_text', toggleActions: 'restart none none none'}, delay: 1, duration: 1.5, opacity: 1, y: 25});
gsap.fromTo('.banner_quote', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.banner_quote', toggleActions: 'restart none none none'}, delay: 1.5, duration: 1.5, opacity: 1, y: 25});
gsap.fromTo('.page_1_text', {opacity: 0, y:25}, {scrollTrigger: {trigger: '.page_1_text', toggleActions: 'restart none none none'}, delay: 2.5, duration: 1, opacity: 1, y: 0});
gsap.fromTo('.preview', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.preview', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.diff', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.diff', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.diff_title', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.diff_title', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.diff_text', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.diff_text', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.flow_chart', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.flow_chart', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.flow_chart_title', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.flow_chart_title', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.flow_chart_img', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.flow_chart_img', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.download_title', {opacity: 0, y:25}, {scrollTrigger: {trigger: '.download_title', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.button', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.button', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.os_name', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.os_name', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.Note', {opacity: 0, y:45}, {scrollTrigger: {trigger: '.Note', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.repo_text', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.repo_text', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.github_link', {opacity: 0, y:50}, {scrollTrigger: {trigger: '.github_link', toggleActions: 'restart none none none'}, duration: 1, delay: .25, opacity: 1, y: 0});
gsap.fromTo('.copy_right', {opacity: 0, y:15}, {scrollTrigger: {trigger: '.copy_right', toggleActions: 'restart none none none'}, duration: 1, opacity: 1, y: 0});