name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'The developers will review your issue and fix it as soon as possible. Thanks for submitting the issue.'
        pr-message: 'Message that will be displayed on users first pull request'
